---
- name: Include common preflight tasks
  ansible.builtin.include_tasks: "common/preflight.yml"
  tags:
    - preflight

- name: Perform setup tasks
  when: not perform_uninstall | bool
  block:
    - name: Include common config tasks
      ansible.builtin.include_tasks: "common/config.yml"
      tags:
        - config

    - name: Include common launch tasks
      ansible.builtin.include_tasks: "common/launch.yml"
      tags:
        - launch
