---
- name: Create unit configuration path
  become: true
  become_user: "{{ _unit_user if _own_as_user else 'root' }}"
  when: unit_item.path is defined
  vars:
    _unit_user: "{{ unit_item.user | default(_default_unit_user) }}"
    _unit_group: "{{ unit_item.group | default(_unit_user) }}"
    _unit_scope: "{{ unit_item.scope | default('user' if _unit_user != 'root' else 'system') }}"
    _unit_home: "{{ ansible_facts.getent_passwd[_unit_user][4] }}"
    _unit_path: "{{ unit_item.path }}"
    _own_as_user: "{{ _unit_scope == 'user' and (_unit_path is match('^' ~ (_unit_home | regex_escape) ~ '(/|$)' )) }}"
  ansible.builtin.file:
    path: "{{ unit_item.path }}"
    state: directory
    owner: "{{ _unit_user if _own_as_user else 'root' }}"
    group: "{{ _unit_group if _own_as_user else 'root' }}"
    mode: "0755"
    follow: false
  loop: "{{ unit_config }}"
  loop_control:
    loop_var: unit_item
    label: "{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
  tags:
    - config

- name: Render systemd unit files
  become: true
  become_user: "{{ _unit_user if _own_as_user else 'root' }}"
  vars:
    config: "{{ unit_item }}"
    unit_dest: "{{ unit_item.path | default(_default_unit_path) }}/{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
    _unit_user: "{{ unit_item.user | default(_default_unit_user) }}"
    _unit_group: "{{ unit_item.group | default(_unit_user) }}"
    _unit_scope: "{{ unit_item.scope | default('user' if _unit_user != 'root' else 'system') }}"
    _unit_home: "{{ ansible_facts.getent_passwd[_unit_user][4] }}"
    _unit_path: "{{ unit_item.path | default(_default_unit_path) }}"
    _own_as_user: "{{ _unit_scope == 'user' and (_unit_path is match('^' ~ (_unit_home | regex_escape) ~ '(/|$)' )) }}"
  ansible.builtin.template:
    src: systemd.unit.j2
    dest: "{{ unit_dest }}"
    owner: "{{ _unit_user if _own_as_user else 'root' }}"
    group: "{{ _unit_group if _own_as_user else 'root' }}"
    mode: "0644"
    backup: "{{ systemd_backup_files | default(_default_systemd_backup_files) }}"
  loop: "{{ unit_config }}"
  loop_control:
    loop_var: unit_item
    label: "{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
  when: unit_item.type | default(_default_unit_type) != 'conf'
  register: render_units
  notify: Reload systemd units
  tags:
    - config
    - molecule-idempotence-notest

- name: Render systemd drop-in files
  become: true
  become_user: "{{ _unit_user if _own_as_user else 'root' }}"
  vars:
    config: "{{ unit_item }}"
    unit_dest: "{{ unit_item.path | default(_default_unit_path) }}/{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
    _unit_user: "{{ unit_item.user | default(_default_unit_user) }}"
    _unit_group: "{{ unit_item.group | default(_unit_user) }}"
    _unit_scope: "{{ unit_item.scope | default('user' if _unit_user != 'root' else 'system') }}"
    _unit_home: "{{ ansible_facts.getent_passwd[_unit_user][4] }}"
    _unit_path: "{{ unit_item.path | default(_default_unit_path) }}"
    _own_as_user: "{{ _unit_scope == 'user' and (_unit_path is match('^' ~ (_unit_home | regex_escape) ~ '(/|$)' )) }}"
  ansible.builtin.template:
    src: override.conf.j2
    dest: "{{ unit_dest }}"
    owner: "{{ _unit_user if _own_as_user else 'root' }}"
    group: "{{ _unit_group if _own_as_user else 'root' }}"
    mode: "0644"
    backup: "{{ systemd_backup_files | default(_default_systemd_backup_files) }}"
  loop: "{{ unit_config }}"
  loop_control:
    loop_var: unit_item
    label: "{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
  when: unit_item.type | default(_default_unit_type) == 'conf'
  register: render_dropins
  notify: Reload systemd daemon
  tags:
    - config
