---
- name: Resolve passwd entries for unit file owners
  when: unit_config | length > 0
  ansible.builtin.getent:
    database: passwd
  tags:
    - preflight

- name: Check for uninstall signal
  when: perform_uninstall | bool
  tags:
    - preflight
  block:
    - name: Broadcast uninstall signal
      ansible.builtin.command: /bin/true
      notify: Uninstall units
      changed_when: true
      tags:
        - molecule-idempotence-notest

    - name: Flush handlers to ensure uninstall is completed
      ansible.builtin.meta: flush_handlers
      tags:
        - molecule-idempotence-notest
