---
name: Continuous-Integration
run-name: CI ${{ github.repository }} - ${{ github.ref }} job 🚀
on:
  push:
    branches: [master]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Lint yaml and Ansible configs
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint==24.6.0 yamllint==1.35.1
          yamllint --config-file ./tests/yaml-lint.yml .
          ansible-lint --config-file ./tests/ansible-lint.yml .
