---
name: Continuous-Integration
run-name: CI ${{ github.repository }} - ${{ github.ref }} job 🚀
on:
  push:
    branches: [master]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Lint yaml and Ansible configs
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          yamllint --config-file ./tests/yaml-lint.yml .
          ansible-lint --config-file ./tests/ansible-lint.yml .

  molecule:
    strategy:
      matrix:
        scenario: [config, launch, uninstall]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Start Docker
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Run Molecule Test
        run: cd tests && molecule --base-config molecule/base.yml test -s ${{ matrix.scenario }}
